### ISSUE TITLE
Existing anchor being replaced by `a*`

### ISSUE THREAD

**Issue by bhargavpanth** [eemeli/yaml#105]
I have been trying to parse a YAML file with anchors like so,
```
version: 2.0
defaults: &defaults
.
.
```
I have been converting the YAML file to a JSON object, manipulating the properties and converting it back to YAML using the following functions respectively `YAML.parse()` and `YAML.stringify()`

Example :
```
const YAML = require('yaml')

const json_obj = YAML.parse('content_of_yaml_file')
//  modifing the jsonObj
YAML.stringify(modified_json_obj)
```
By `stringify`ing the `modified_json_obj` I noticed that I was loosing the anchor values and was being replaced by `a`, `a1`...
I feel I am missing the `options = { }` parameter while I call the `parse` method. But I'm unable to understand what the value for the `anchorPrefix` should be in order to retain the anchor value.

Sample after I convert the `modified_json_obj`
```
version: 2
defaults:
  &a1
.
.
.
```

**Comment by eemeli** [comment]
When using `YAML.parse()`, you end up with a JS representation of just the _data_ held by the YAML source, while the anchor names are a part of the _metadata_.

In order to keep the anchor names you start with, you should use `YAML.parseDocument()` rather than `YAML.parse()`. This'll get you a [Document](https://eemeli.org/yaml/#documents) object that retains relevant metadata such as the anchor names, and provides e.g. getter and setter methods to apply the modifications that you need.

**Comment by sourcevault** [comment]
`yaml.parseDocument(docstring)` doesn't preserve anchor name, and replaces them with `a1,a2,a3,......`
