### ISSUE TITLE
Trouble encoding with custom types to yaml...

### ISSUE THREAD

**Issue by acklavidian** [eemeli/yaml#111]
So I've compiled a condensed version of the problem I am having here: 
https://codesandbox.io/s/yaml2json2yaml-qiid6

Basically I want to be able to recreate the `!binary` tag when the data gets transcribed back to yaml. Any guidance would be appreciated. Thank you.

**Comment by eemeli** [comment]
Would the default [`!!binary`](https://eemeli.org/yaml/#custom-data-types) tag work for you?

**Comment by acklavidian** [comment]
@eemeil Not sure if you mean importing the type and overriding the the tag to be '!binary' instead of '!!binary'. I tried and it still doesn't work in my experience. 

If you mean to change the tag in the yaml it's self then no. I don't have any control over that. :(

**Comment by eemeli** [comment]
Okay, the following is sort of horribly hacky but might work:

```js
const yml = `...`
const doc = YAML.parseDocument(yml, { version: '1.0' })
doc.options.version = '1.1'
const binNode = doc.getIn(['settings', 1, 'value'], true)
binNode.value // <Buffer 3d 4e dd a5 bf ...>
binNode.tag = '!binary'
String(doc)
```

What's happening there is that you read the original input as YAML 1.0, which used `!` as the default prefix, rather than the `!!` of YAML 1.1 and 1.2, and hence matches `!binary` to the common binary tag. Just stringifying that does use the full form `!yaml.org,2002:binary` for YAML 1.0, so we then switch the version to `1.1`, and set the binary node's tag to a local tag `!binary`. This needs to happen using the document level API, in order to get access to this metadata.

Another differently hacky alternative would be for you to locally modify the binary tag before using it:

```js
const bin = require('yaml/dist/tags/yaml-1.1/binary').default
bin.tag = '!binary'
YAML.defaultOptions.customTags = ['binary']

const yml = `...`
const obj = YAML.parse(yml)
YAML.stringify(obj)
// description: Just an example...
// settings:
//   - key: activity
//     type: attribute
//     value: "234"
//   - key: activity-secret
//     type: attribute
//     storage: encrypted
//     value: !binary |-
//       PU7dpb9YLMAE0X9xRrYYtHWBO60EaZsEJd1ujNHP1rBlgm4XmBuC+LPH8FdVJdgN
```

**Comment by acklavidian** [comment]
Thank you so much. Your second option worked well for my use case. It might be worth mentioning for future inquiries that I also had to make sure to ensure my data type wasn't getting destroyed when passed via json over a network.
