### ISSUE TITLE
Empty lines spacer

### ISSUE THREAD

**Issue by Micene09** [eemeli/yaml#115]
Everything is working good, but as i see i'm not able to keep empty line on parse method.
Empty lines works like a spacer to improve the readability.

Example:
```javascript
const yaml = require("yaml");
const ymlFile = fs.readFileSync("./file.yml", "utf-8");  // << file with empty lines before every node
let parsedYml = yaml.parse(ymlFile);

// ...editing parsedYml's props here...

fs.writeFileSync("./file.yml", yaml.stringify(parsedYml));
```
...the new file.yml here will not have any space before every node, making it unreadable for me.

A good solution should be to add a new prop on option parameter for `stringify` method, example: "space(s)Before" (boolean, o number...).

**Comment by eemeli** [comment]
If you're intending to read, modify, and then re-stringify a YAML file while keeping its general structure, you should use the [YAML Document API](https://eemeli.org/yaml/#documents) instead of the parse/stringify API. In addition to keeping empty lines, this will keep comments and other structural features at least close to how they were in the original. The document also provides a number of accessor methods that should make it relatively easy to access and modify values within your structure.

But you're also right that having an automatic spacer might also be nice for `YAML.stringify()` and `new YAML.Document`. The API for that option will need some thought, though, as it'll probably need to be controllable at least according to the depth of the document structure.

**Comment by Micene09** [comment]
> If you're intending to read, modify, and then re-stringify a YAML file while keeping its general structure, you should use the [YAML Document API](https://eemeli.org/yaml/#documents) instead of the parse/stringify API.

ok...got it!
here is the full working example code:

```javascript
const yaml = require("yaml");
const ymlFile = fs.readFileSync("./file.yml", "utf-8");
let parsedYml = yaml.parseDocument(ymlFile);

// ...editing parsedYml's props here...
parsedYml.setIn(["prop1", "nestedProp"], "asd");
parsedYml.set("prop2", "lol");

fs.writeFileSync("./file.yml", parsedYml.toString());
```
...[here](https://eemeli.org/yaml/#collections) is the full list of methods to navigate/manipulate the parsed document.

**Comment by eemeli** [comment]
Closing this as answered/stale. I'd kept it open to account for the "automatic spacer" idea, but that's best raised as a separate issue or PR.
