### ISSUE TITLE
How can one disambiguate a string that looks like a date?

### ISSUE THREAD

**Issue by nulltoken** [eemeli/yaml#117]
Hello,

```
console.log(require("yaml").stringify({a: "1", b: "b", c: "2012-10-12"}))
```

returns

```
a: "1"
b: b
c: 2012-10-12
```

Would there be a way to keep the value of `c` quoted so that it wouldn't be interpreted as a timestamp by parsers?

**Comment by eemeli** [comment]
The `yaml` stringifier verifies that its output will also be parsed to the same type as its input; this is why the string `"1"` gets stringified as `"1"`, rather than just `1`. What's happening here with `"2012-10-12"` is that the re-parsing test is defaulting to use the YAML core schema, which does not include timestamps as a data type, and hence allows the default unquoted style to be used.

In order to make sure that your date-ish string also gets quoted, the most appropriate thing to do is to specify either the `schema` or `version` in your [options](https://eemeli.org/yaml/#options):
```js
YAML.stringify(obj, { version: '1.1' })
```

To really fine-tune your stringification, you'll need to construct a `YAML.Document` and set the `type` value for your [scalar nodes](https://eemeli.org/yaml/#scalar-values).

**Comment by nulltoken** [comment]
Another great thoroughly detailed answer! Thanks.
