### ISSUE TITLE
Turning off warning logs

### ISSUE THREAD

**Issue by wesleytodd** [eemeli/yaml#148]
It seems that there is no way to turn off warning logs without passing `--no-warnings` to the node process.  Am I just missing the docs somewhere on how to do this?

This is very much less than ideal when using this in an application as it would also turn off node warnings. It makes me wonder why this library uses the `emitWarning` api?  A few approaches which might be more user friendly would be:

1. Accept a `noWarnings` option and [disable even the `console.warn` in here](https://github.com/eemeli/yaml/blob/master/src/warnings.js#L3-L13)
2. Accept a custom logging implementation (like a `pino` instance) as an option
3. Expose a warning interface on the main export, (ex. `yaml.on('warning', ...)`)

The first option is the most simple, but is less flexible for others who might want more than *just* turning them off.  The others would give users much more control on the behavior of their application output.  Thoughts on this?  

---

EDIT:

This is what I am doing right now before calling `yaml.parse`:

```javascript
// Suppress yaml errors
const origWarning = process.listeners('warning')[0]
process.off('warning', origWarning)
function suppressYamlWarnings (warning) {
  if (warning.name === 'YAMLWarning') return
  origWarning(warning)
}
process.on('warning', suppressYamlWarnings)

// ...
// my yaml handling code
// ...

// Re-enable warning logging
process.off('warning', suppressYamlWarnings)
process.on('warning', origWarning)
```

The big drawback of this is that it relies on node registering it's warning handler as the first handler (pretty reliable but should be an implementation detail of node), but also this is just crazy to have in my application code.

**Comment by eemeli** [comment]
This needs better documentation, or perhaps an improved API? Setting a global variable `_YAML_SILENCE_WARNINGS` to true will silence all warnings, and setting `_YAML_SILENCE_DEPRECATION_WARNINGS` will silence all deprecation warnings in particular.

**Comment by wesleytodd** [comment]
Hey!  Yeah docs on that would be good, I didn't know about that env variable.  That said, setting something on `process.env` in the process is not a common interface, and arguably I only want to turn it off for the calls my code makes, so setting it as an option would be a good addition as well.

**Comment by eemeli** [comment]
Adding an option for silencing warnings is not in fact that straightforward. There are two general categories of warnings emitted by `yaml`:
1. Deprecated APIs, e.g. using `import Pair from 'yaml/pair'` rather than `import { Pair } from 'yaml/types'`
2. Warnings specified and required by the YAML spec

For the deprecation warnings, it's not possible to use any options object, as they need to trigger even if `'yaml'` itself is never imported. Hence the need to use a global variable to allow silencing them.

For the YAML spec parser warnings, those are emitted by the `YAML.parse()` wrapper, which is defined like this:

```js
function parse(src, options) {
  const doc = parseDocument(src, options)
  doc.warnings.forEach(warning => warn(warning))
  if (doc.errors.length > 0) throw doc.errors[0]
  return doc.toJSON()
}
```

So while it would be possible to add an option to silence them, I'd really rather not, because 1) that'd mean that there would need to be two completely different warning-silencing APIs and 2) the workaround of defining your own `parse()` which doesn't warn is pretty easy.

But yeah, I'll add a note about the warnings to the docs. The variables, btw, need to be on `global` or `window` (depending on context) rather than `process.env`.

**Comment by eemeli** [comment]
Added a section to the docs & dropped the leading `_` from the variable names. Also now checking `process.env` for silencing globals.

**Comment by wesleytodd** [comment]
Hm, I am still not sold on the whole thing, but I understand your opinions.  In the case of taking in yaml you don't control it is REALLY unfortunate to has this difficult api.  I don't really care that it is warnings specified by the yaml spec, I only care to see failure to parse errors, and this module outputting to the console is undesirable.  If you ever reconsider, consider this a strong 👍 to changing this behavior from me.
