### ISSUE TITLE
questionable code in BlankLine.js

### ISSUE THREAD

**Issue by BurtHarris** [eemeli/yaml#150]
In BlankLine.js, the following code seems without effect, because `Node.endOfWhiteSpace` returns a number, not a string:

```javascript
const lineEnd = Node.endOfWhiteSpace(src, offset)
      if (lineEnd === '\n') offset = lineEnd + 1
      else break
```

**Comment by eemeli** [comment]
Huh, that's an unfortunate bug. It really should be `if (src[lineEnd] === '\n) ...`.

This means that atm the CST parser generates separate nodes for each consecutive blank line, rather than one node that spans multiple blank lines, as I'd intended. Which isn't necessarily incorrect, it's just _different_.

I think the right thing to do here is to roll with it, and to not change the current behaviour. I'll clean up the code accordingly.
