### ISSUE TITLE
TypeScript errors with 1.9.x

### ISSUE THREAD

**Issue by acherniak** [eemeli/yaml#158]
After upgade to 1.9 the line `import YAML from 'yaml';` fails in VS Code `Module '".../node_modules/yaml/index"' has no default export.ts (1192)` in my Angular application.
It still works with 1.8.3
Changing to `import * as YAML from 'yaml';` errors with a message `export 'parse' (imported as 'YAML') was not found in 'yaml'`
Please advise.

**Comment by cmoesel** [comment]
Hi @acherniak -- I'm just another user of the library, but I am using VS Code with TypeScript and yaml 1.9.2 and I am not seeing this problem.  I can successfully use `import YAML from 'yaml';` in my project.

A few things to consider:
* yaml 1.9.x added TS types natively to the package (#153) so if you are using `@types/yaml`, you should probably remove it from your dependencies
* I find that sometimes when I encounter errors like this, I simply need to restart VS Code (especially after upgrading TS or TS type libraries)
* I am using VS Code 1.44.2 and TypeScript 3.7.2

I don't know if any of that will help, but maybe?

**Comment by acherniak** [comment]
@cmoesel, I couldn't find @types/yaml anywhere (even globally) although vaguely remember installing it at some point. Should 1.8.2 work with typescript at all without @types/yaml?
I also use the latest VS Code, but downgrade TS to 3.7.2 didn't help. Neither did multiple restarts.

**Comment by cmoesel** [comment]
When I was using a previous version of yaml, I needed to have `@types/yaml` as a devDependency in order for VSCode to properly recognize the types.  I don't recall exactly what happened if I did not have it.

Sorry for making you try downgrading to TS 3.7.2, and even more sorry it didn't work!  I'm afraid I have no other ideas.  Like I said, it just works for me...  I doubt it makes a difference, but I am on Mac...

**Comment by eemeli** [comment]
The `@types/yaml` package hadn't been updated much since about `yaml@1.2`; that was one reason for adding the types directly to the package in `yaml@1.9`. Downgrading to `yaml@1.8` will mean that any typing info will come from somewhere other than `yaml` itself.

I think the difference here might be that @cmoesel's TS config includes `allowSyntheticDefaultImports: true` while @acherniak's doesn't. Is this the case?

The library itself is published as CommonJS, such that `require('yaml')` gives you an object with the main API methods as members, so it doesn't technically have a "default" export. However, in a Node.js ES module context, `import YAML from 'yaml'` will definitely work, so it's kinda like a default export? Is there some common practice about what to do for TS types in this case?

**Comment by eemeli** [comment]
As for `import * as YAML from 'yaml'` causing the other error you reported, that I don't have an explanation for. I'm also unable to reproduce that error locally. Does that error also appear when you run `tsc` from the command line, or just in VS Code?

**Comment by cmoesel** [comment]
> I think the difference here might be that @cmoesel's TS config includes allowSyntheticDefaultImports: true while @acherniak's doesn't. Is this the case?

Ah, good point!  I am using it in the context of Node.js and I do have this config which "implies 'allowSyntheticDefaultImports'."
```
"esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
```

**Comment by acherniak** [comment]
`allowSyntheticDefaultImports: true` fixed it. Thank you for all the help.
Great package!
