### ISSUE TITLE
Can't handle single-quoted multiline strings without indents

### ISSUE THREAD

**Issue by erunion** [eemeli/yaml#176]
The following YAML throws a "Multi-line single-quoted string needs to be sufficiently indented" error.

```yaml
description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Suspendisse vehicula ex et nulla ultricies elementum. Nam massa nisi,
accumsan ac eros sed, maximus consectetur libero. Aliquam quis vehicula
lacus. Fusce iaculis fringilla accumsan.'
```

I know there's unit tests to assert this case, but writing strings this way is valid YAML: https://yaml-multiline.info/

I'm happy to attempt to submit a PR to support this, I'm just wondering what the reasoning behind not supporting it is and if you would be open to accepting a PR for it.

**Comment by perlpunk** [comment]
This is not valid, and the information on https://yaml-multiline.info/ is wrong.
The spec requires all nodes to be indented more than their parent nodes, even if enclosed in quotes, `{}` or `[]`.
It is correct that several YAML processors allow this, though.

IMHO this shouldn't be allowed. It will break indent-folding in editors and makes YAML harder to read.

**Comment by eemeli** [comment]
As @perlpunk mentions, the `yaml` error is valid. I've filed an issue to get this fixed in the linked-to documentation site.

**Comment by erunion** [comment]
That's understandable, it's just difficult as most other parsers are able to handle strings formatted that way and I've got customers of ours pointing towards those other parsers and asking us "why can't you validate this but everyone else can?"

**Comment by eemeli** [comment]
Then I would encourage you to reach out to those other parsers, and raise an issue with them that they're breaking with the YAML spec, and that this is causing interoperability issues with their users.

**Comment by erunion** [comment]
That's kind of an unreasonable request. Can't an option be introduced here go allow for lazy/non-strict multiline acceptance? The library is able to parse these strings fine given the error messages, I don't think it being "proper" really matters here.

**Comment by eemeli** [comment]
You're right, the invalid YAML is being parsed as you'd expect by the library, at least in this case.

If you'd like to make use of the results, you should use `YAML.parseDocument(src)` rather than `YAML.parse(src)`, and then handle or dismiss the `doc.errors` array of errors as necessary. If you then set the length of `doc.errors` to zero, calling `doc.toJSON()` won't throw. But it might not always give you exactly the results you're expecting, if the invalid input has been interpreted differently than you'd expect.

I would still encourage you to get this fixed at the source, either by fixing the emitter for this invalid YAML, or by updating your guidance to your users.

Out of interest, could you specify which "most other parsers" don't complain about this input?

**Comment by saraid** [comment]
I'm not familiar with a lot of different parsers, but here are some that seem widely used.

Node:
```js
const { parse } = require('yaml');
parse("foo: 'single-quoted\nunindented text'")
//=> Uncaught: YAMLSemanticError: Multi-line single-quoted string needs to be sufficiently indented
```

Ruby, using the stdlib-packaged library:
```ruby
require 'yaml'
YAML.load(<<~YAML)
foo: 'single-quoted
unindented text'
YAML
#=> {"foo"=>"single-quoted unindented text"}
```

Using PyYAML,
```python
>>> import yaml
>>> text = "foo: 'single-quoted\nunindented text'"
>>> yaml.safe_load(text)
{'foo': 'single-quoted unindented text'}
```

Jackson library for Java also handles it fine:
```java
import java.io.File;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.fasterxml.jackson.databind.ObjectMapper;

public class Main {
  public static void main(String[] args) throws Exception{
    ObjectMapper yamlMapper = new ObjectMapper(new YAMLFactory());
    ObjectMapper jsonMapper = new ObjectMapper();
    System.out.println(jsonMapper.writeValueAsString(yamlMapper.readTree(new File(args[0])))));
  }
}
```

YamlElixir for Elixir:
```elixir
iex(1)> yaml = """
...(1)> foo: 'single-quoted
...(1)> unindented text'
...(1)> """
"foo: 'single-quoted\nunindented text'\n"
iex(2)> YamlElixir.read_from_string(yaml)
{:ok, %{"foo" => "single-quoted unindented text"}}
```

I agree that unindented text is definitely a format that should be discouraged, but that should be the concern of stringifiers rather than parsers. This seems to be the only YAML parser that actually follows this particular aspect of the specification (and I'm sympathetic to sticking closely to it; that's absolutely the best practice in general).
