### ISSUE TITLE
Key lengths limited to 1024 characters?

### ISSUE THREAD

**Issue by MikeRalphson** [eemeli/yaml#183]
I'm hitting a real-world example of a key with a length greater than 1024 characters. This module seems to explicitly check for this, but I had a quick grep through the YAML 1.2 spec and could not find this constant referenced anywhere.

https://github.com/eemeli/yaml/search?q=1024

Commenting out the checks doesn't seem to have any adverse effects, and I guess, improves performance. Could this at least be made configurable if it is a resource-exhaustion guard?

**Comment by eemeli** [comment]
It's in [section 7.4.2](https://yaml.org/spec/1.2/spec.html#id2790832) of the YAML 1.2 spec:
>If the “?” indicator is omitted, parsing needs to see past the implicit key to recognize it as such. To limit the amount of lookahead required, the “:” indicator must appear at most 1024 Unicode characters beyond the start of the key. In addition, the key is restricted to a single line.

This limitation is likely to get dropped in the next version of the YAML spec, in which case at least some functionality will get introduced to skip this check. Before that happens, I'm really rather disinclined to add special configuration for allowing what's actually invalid YAML.

If you do need to skip this error in particular, something like this should work:

```js
function parseWithLongKeys(src) {
  const doc = YAML.parseDocument(src)
  for (const error of doc.errors) {
    if (!error.message.includes('key is too long') throw error
  }
  doc.errors.length = 0
  return doc.toJSON()
}
```

For `yaml@2`, I should add constant string codes to the errors, so that they can be more certainly identified.

**Comment by MikeRalphson** [comment]
Apologies, I don't know why I didn't find that occurrence in the spec. Closing as not a bug. Thanks again.

**Comment by Fndroid** [comment]
Sorry to comment on a closed issue.

It seems that setting directive like `%YAML 1.1` still got this error, it might be a glitch i guess?

**Comment by eemeli** [comment]
@Fndroid If you think there's a current bug with the library, please file a new issue.
