### ISSUE TITLE
Update key

### ISSUE THREAD

**Issue by igor-lemon** [eemeli/yaml#184]
Hi. Can I update a key in some item in a collection?
An example I have:
```
{
 foo: 123,
 bar: 456,
 someKey: 789
}
```
and I want to change the `bar` key to `barNew` and have the final result as 
```
{
 foo: 123,
 barNew: 456,
 someKey: 789
}
```

Is it possible?

**Comment by eemeli** [comment]
Yes.
```js
const doc = YAML.parseDocument(src)
const bar = doc.contents.items.find(pair => pair.key.value === 'bar')
bar.key.value = 'barNew'
String(doc)
// '{ foo: 123, barNew: 456, someKey: 789 }\n'
```

The result of [`parseDocument`](https://eemeli.org/yaml/#parsing-documents) is a document object, which holds the data object in `doc.contents`. In this case, that's a [mapping](https://eemeli.org/yaml/#collections), which has an array `items` of its constituent key/value pairs. In this case, each of those pairs has a [scalar](https://eemeli.org/yaml/#scalar-values) key, which provides a `value` that can be used to identify the key you're looking for.

The single-line representation of the mapping in the stringified output is due to its shortness. With a real-world example, you're likely to run against the default 80 char line length limit, and get output in the form that you're expecting.

Because updating values is far more common, a shortcut is provided for that: `doc.set('bar', 'barNewValue')`.

**Comment by igor-lemon** [comment]
Thanks for the answer!
