### ISSUE TITLE
Duplicate comment in MAP items

### ISSUE THREAD

**Issue by ikatyang** [eemeli/yaml#19]
This only happens if there's no trailing newline.

Version: 1.0.0-rc.7

Input

```yaml
a:
  # 123
```

Output

```json5
[
  { type: "PLAIN" },
  { type: "MAP_VALUE", comment: "123" },
  { type: "COMMENT", comment: "123" }
]
```

Expected

```json5
[
  { type: "PLAIN" },
  { type: "MAP_VALUE", comment: "123" }
]
```

Original post: prettier/prettier#4861

**Comment by eemeli** [comment]
Thank you, this should now be fixed in the next release. The bug here was with the parsing offset getting incorrectly reset to the line-start for a collection item with an empty value not followed by a newline at the document end, so a bit of a corner-case.

However, fixing that bug revealed another; comments on mappings with empty values were getting dropped at the `parseDocument` level, as the code accounting for those is a part of the value-parsing code that depends on a reference to the node's parent, and e.g. in this case that value ends up being `null` rather than a fully-qualified node. To fix that, an empty plain node is now constructed for such a comment to attach to during parsing. As a result, we get this:
```js
const doc = YAML.parseDocument('a: # 123')
String(doc) === 'a: null # 123\n'
```
