### ISSUE TITLE
[discussion] The QuoteDouble Scalar parsing rule 

### ISSUE THREAD

**Issue by dota17** [eemeli/yaml#191]
When eemeli/yaml parses the QuoteDouble Scalar which contains line break like `demo1`, eemeli/yaml will throw an exception. This result is different from pyyaml. The pyyaml output is `a: aaa bbb`. For QuoteDouble Scalars in block format. eemeli/yaml checks indents after line breaks.
```yml
# demo1:
   a:"aaa
bbb"
```

In addition, for a escaped line break `\n` in  QuoteDouble Scalar. eemeli/yaml folds the line and parses the `\n` as white space ` `. and pyyaml retains the `\n`. Which one is better?
```yml
a;"aaa\nbbb"
```

**Comment by eemeli** [comment]
"Better" is of course a subjective term, but `yaml` follows the v1.2 spec. For double-quoted strings, [Section 7.3.1](https://yaml.org/spec/1.2/spec.html#id2787109) is the authoritative source; note the link onwards from there to read exactly what "flow line folding" should mean in YAML

As for your first example, it's an error because it's invalid YAML: With the key/value pair being indented by three spaces, lines after the first must have at least four spaces of indentation.
