### ISSUE TITLE
SyntaxError: Sequence items are not allowed on the same line with map keys

### ISSUE THREAD

**Issue by ikatyang** [eemeli/yaml#2]
First of all, thanks for the great parser so that I can use it to [add YAML support in Prettier](https://github.com/prettier/prettier/pull/4563).

---

(from https://github.com/prettier/prettier/pull/4563#issuecomment-392356228)

version: 1.0.0-beta.5

input:

```yaml
aliases:
  - docker:
      - image: circleci/node:8.11.2
  - key: repository-{{ .Revision }}
```

output:

```js
[ { type: "DOCUMENT", contents: [ 
    { type: "MAP", items: [
        { type: "PLAIN", strValue: "aliases" },
        { type: "MAP_VALUE", node: {
            type: "SEQ", items: [
                { type: "SEQ_ITEM", node: { 
                    type: "MAP", items: [
                        { type: "PLAIN", strValue: "docker" },
                        { type: "MAP_VALUE", node: {
                            type: "SEQ", items: [
                                { type: "SEQ_ITEM", node: {
                                    type: "MAP", items: [
                                        { type: "PLAIN", strValue: "image" },
                                        { type: "MAP_VALUE", node: {
                                            type: "PLAIN", strValue: "circleci/node:8.11.2"
    } } ] } } ] } } ] } } ] } } ] },
    { type: "SEQ", items: [
        { type: "SEQ_ITEM", node: {
            type: "MAP", items: [
                { type: "PLAIN", strValue: "key" },
                { type: "MAP_VALUE", node: {
                    type: "PLAIN", strValue: "repository-{{ .Revision }}"
} } ] } } ] } ] } ]
```

```
SyntaxError: Sequence items are not allowed on the same line with map keys (4:3)
  2 |   - docker:
  3 |     - image: circleci/node:8.11.2
> 4 |   - key: repository-{{ .Revision }}
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  5 | 
```

expected:

```js
[ { type: "DOCUMENT", contents: [
    { type: "MAP", items: [
        { type: "PLAIN", strValue: "aliases" },
        { type: "MAP_VALUE", node: {
            type: "SEQ", items: [
                { type: "SEQ_ITEM", node: {
                    type: "MAP", items: [
                        { type: "PLAIN", strValue: "docker" },
                        { type: "MAP_VALUE", node: {
                            type: "SEQ", items: [
                                { type: "SEQ_ITEM", node: {
                                    type: "MAP", items: [
                                        { type: "PLAIN", strValue: "image" },
                                        { type: "MAP_VALUE", node: {
                                            type: "PLAIN", strValue: "circleci/node:8.11.2"
                } } ] } } ] } } ] } }
                { type: "SEQ_ITEM", node: {
                    type: "MAP", items: [
                        { type: "PLAIN", strValue: "key" },
                        { type: "MAP_VALUE", node: {
                            type: "PLAIN", strValue: "repository-{{ .Revision }}"
} } ] } } ] } } ] } ] } ]
```

with no error.

**Comment by eemeli** [comment]
That was an interesting bug to track down; thank you for bringing it to my attention!

When parsing the source into the AST, we detect a collection starting from the first collection item, and base the parsing context for the collection on the parsing context of the (already parsed) first item. In the particular case where the first item of a collection is itself a block collection and the outer collection has a positive indent level, the outer collection's first item's `lineStart` index was incorrectly used to initialise the parsing of the second collection item, which then fails because it ends up considering an extraneous un-indent step to have been taken.

I fixed this by forcing a recalculation of the initial `lineStart` at the start of the collection parse, as that turns out to be much more robust than trying to track down the immediately preceding node (which could be somewhere really deep if the first item is complicated) and grabbing its `lineStart` value.

I'll package another beta release either today or tomorrow that'll include this fix, as well as an earlier fix for the extraneous "Node#parse consumed no characters" errors.

**Comment by eemeli** [comment]
Drat, I spoke too soon. It turns out that there's some other bug that this code is also encountering.
