### ISSUE TITLE
Question: render as JSON-style sequence

### ISSUE THREAD

**Issue by privatenumber** [eemeli/yaml#204]
In `YAML.stringify`, is it possible to configure the stringifier to render _specific keys_ with a JSON-style sequence as opposed the list-style sequene?

JSON-style sequence:
```yaml
json-style-sequence: [1, 2, 3, 4]
```

List-style sequence:
```yaml
list-style-sequence:
  - 1
  - 2
  - 3
  - 4
```

**Comment by eemeli** [comment]
To achieve that, you'll need to create a YAML.Document from your original object, and then set the `type` as `'FLOW_SEQ'` or `'FLOW_MAP'` on the appropriate nodes, and then stringify the Document:

```js
const doc = new YAML.Document({
  'json-style-sequence': [1, 2, 3, 4],
  'list-style-sequence': [1, 2, 3, 4]
})
doc.get('json-style-sequence').type = 'FLOW_SEQ'
String(doc)
```

```yaml
json-style-sequence: [ 1, 2, 3, 4 ]
list-style-sequence:
  - 1
  - 2
  - 3
  - 4
```

In the documentation, you'll find this mentioned in the [collections](https://eemeli.org/yaml/#collections) section. If you have an idea of a more ergonomic API for achieving this, I'd be very interested to hear.

**Comment by privatenumber** [comment]
That's great! Thanks for the thorough explanation & example.

Intuitively, I wondered if I could pass into `YAML.stringify` a function similar to `JSON.stringify`'s `replacer`  to indicate whether a key-value pair should be a `FLOW_SEQ` or `SEQ`. I'm not sure if that covers all use-cases though.

**Comment by eemeli** [comment]
For simplicity and to match the JSON spec, the `replacer` only applies filtering and transformations to the JS values that are only afterwards mapped to YAML nodes. In particular because of the process starting from the outside and working inwards, it'd be rather clumsy to expect node construction to happen within a replacer call, as that would currently be required to e.g. set the resulting node's `type`.

In #190 there's discussion about adding a `visitor` for documents that could provide an API for this sort of transformation, but now I'm also pondering whether it might be worth it to add something like `setProps` as a third argument to the `replacer`, in order to set not just the `type`, but also to force a particular tag to be used for it.

**Comment by privatenumber** [comment]
@eemeli 

That sounds great and would support my use-case well. I want to render all homogenous arrays/lists with primitive values to render as a `FLOW_SEQ`, and only render arrays/lists with objects/arrays with `SEQ`.
