### ISSUE TITLE
Octal numbers are parsed incorrectly

### ISSUE THREAD

**Issue by eladb** [eemeli/yaml#205]
Repro:

```js
console.log(YAML.parse('foo: 0666'))
```

Outputs:

```js
{ foo: 666 }
```

Expected:

```js
{ foo: 438 }
```

**Comment by eemeli** [comment]
`yaml` defaults to using the [YAML 1.2 "core" schema](https://yaml.org/spec/1.2/spec.html#id2805071), which requires octal values to have an `0o` prefix:
```js
YAML.parse('0o666') === 438
```

Your expectation appears to follow the [YAML 1.1 `!!int` spec](https://yaml.org/type/int.html). To use that, you should specify the version:
```js
YAML.parse('0666', { version: '1.1' }) === 438
```
or the schema:
```js
YAML.parse('0666', { schema: 'yaml-1.1' }) === 438
```

**Comment by eladb** [comment]
Cool. Closing.

BTW, is there a way to allow for both formats?

**Comment by eemeli** [comment]
Presuming that you mean "both formats" to refer to just octal values, it is certainly possible for you to write a [custom tag](https://eemeli.org/yaml/#writing-custom-tags) for `0666` to also be parsed as an octal value. But is this library the only one you're using to consume these YAML files? If you start customising, you'll need to use the same custom schema in all its consumers, and that might not be so easy.

My recommendation would be to use just YAML 1.2, as its core schema solves many of the issues caused by the lax rules of YAML 1.1.
