### ISSUE TITLE
Generic stringify for custom types

### ISSUE THREAD

**Issue by qraynaud** [eemeli/yaml#246]
**Is your feature request related to a problem? Please describe.**
I’m created a [higher level API to use custom types for an usage of my own](https://heptapod.lsystems.fr/lsystems/config.io/-/blob/04317a31840dca92ad5815d7be02f2a327d918cd/src/create-tag.mjs). It worked perfectly up to version 1.9.2 but stopped working since 1.10.0. This is because I was using the undocumented `ctx.doc.schema.stringify` method just like that:

```js
const superStringify = (value, ctx, onComment, onChompKeep) => {
  return (typeof value === 'object' ? '\n' + ctx.indent : '') +
    ctx.doc.schema.stringify(value, ctx, onComment, onChompKeep)
}

const someTag = {
  // ...
  stringify(item, ...args) {
    const data = // get some arbitrary data from item
    return superStringify(data, ...args)
  }
}
```

**Describe the solution you'd like**
I'm pretty sure it was a hack, but it still saved my life.

I think it would be awesome if we could get a proper generic stringify method written for this that could take a plain JS object and render it properly in the current context.

**Comment by eemeli** [comment]
Could you give an example of a JS object that you'd like to stringify, and the output that you'd like of it? It should be possible to achieve what you want without a custom stringifier, as the default one is applied automatically.

**Comment by qraynaud** [comment]
Yes sure. Here is a relatively simple use case : https://heptapod.lsystems.fr/lsystems/config.io/-/blob/a5b91f20acb571c4bb92e784d49a96c9f1f6d6ca/src/tags/path.mjs

The relevant part is there:

```js
toYAML (data) {
return data.path.length > 1
  ? data.path
  : typeof data.path[0] === 'object' ? { value: data.path[0] } : data.path[0]
}
```

As you can see, the object has 2 representations and the serializer picks the most appropriate one depending on the context. It returns the correct representation as a plain JS object that is then serialized using the code I provided earlier.

**Comment by eemeli** [comment]
Would it be appropriate to add a [toJSON() method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#tojson_behavior) to the object that would perform this transform? That would get called automatically when the YAML node is created during the stringification.

**Comment by qraynaud** [comment]
You mean it’s already working?

Because I tried to put a toJSON method on my objects and it never got called. If it’s not implemented yet, I'd rather have a toYAML method that would work the same as the toJSON method. It would still be possible to have one that calls the other if we want to.

**Comment by eemeli** [comment]
Perhaps I'm not understanding your usage pattern right?

The way it's intended to work, there are two steps when getting from a pure-JS representation to a YAML string representation of the data:
1. First, the data is mapped to nodes (`doc.createNode(data)`). This is the stage at which `toJSON` methods get called and a replacer function can do additional tuning.
2. Next, each node is stringified. If the node's tag includes a stringifier, that's called; otherwise `stringifyString()` is used for scalars, and collections have their `toString()` methods called.

The `YAML.stringify()` API is effectively a convenience wrapper that takes both of these steps in one go.

It's unclear to me if your source data is pure JS, or if it's meant to already be YAML nodes. If it's the former, then the node creation should allow for powerful tooling to shape the data as you want it. If it's the latter, then it's too late to apply its transforms, and indeed a custom stringifier ought to be used. For that, a custom tag for a scalar value could make use of the publicly accessible `stringifyString()` for scalar values. To format the output as a collection, your best bet would be to create a new temporary node, and to call its `toString()` method: `doc.createNode({ value: 'foo' }).toString(ctx, onComment, onChompKeep)`.

Does that help, or could you describe in more detail how your intended system works?

**Comment by qraynaud** [comment]
I don’t use `YAML.stringify()`. Since the document was parsed from a file I want to retain its comments and such. So I create myself a `Document` using `new` and I then call `doc.parse(YAML.parseCST(str))`. To stringify I then use `doc.toString()`.

Maybe it’s for that reason that I can’t use `toJSON()`? Wouldn’t it be better if the toJSON method was called later in the process? It’s a little disturbing that depending on how the stringification process is called you get different results with custom types. I think they are confusing right now and that it would be easier if they did have a more consistent behavior. I think I’m a rather correct dev, I read your codebase to get to my previous implementation, and I'm very lost with the internals there.

**Comment by qraynaud** [comment]
I just tried to update my stringify function so it reads like this:
```js
if (typeof value !== 'object') {
  return stringifyString({ value }, ctx, onComment, onChompKeep)
}
return ctx.doc.createNode(value).toString(ctx, onComment, onChompKeep)
```

It throws an Error saying that `ctx.doc.createNode` is not a function. When logging `ctx.doc` it’s a proper `Document`. Any idea why?

**Comment by eemeli** [comment]
Ah, sorry, that's the right function to call in `yaml@1`. The API changes in v2.

**Comment by qraynaud** [comment]
Ok thanks! It works like a charm to write this. Do you think there is something to improve over this use case − I think this bug is still valid and there is a need for some more consistent (& elegant) way to stringify custom types. If so I keep this bug open and I'm willing to discuss this here. If not I'm also okay to close it!

**Comment by eemeli** [comment]
The difficulty here is arising from the way that the library assumes that a node in a document is either a scalar, a map, or a sequence, because those are the base types that YAML itself provides. And the nodes that you're stringifying want to get stringified as any one of those options, depending on their internal value. Therefore, a custom stringifier is indeed the right thing to use here.

I'm open to brainstorming about improving the API. It's tricky, really, because there are four stages that need to be considered:
1. node composition from CST
2. transform from node to native JS
3. node creation from native JS
4. node stringification

The current structure isn't really optimal for cases where one of these stages can have more than one different output, as you have here.

I'm happy that you're finding a workable solution, though! In the last code sample that you posted, it shouldn't be necessary to include the `'\n' + ctx.indent` prefix, but presumably the outputs aren't valid without that?

**Comment by qraynaud** [comment]
Yes. If the current stringifying process happens in a property of an object I get results like this:
```yaml
test: !tagname attr1: value1
  attr2: value2
```
instead of:
```yaml
test: !tagname
  attr1: value1
  attr2: value2
```

**Comment by qraynaud** [comment]
Back to the main topic, why not keep the JS custom type in the node and move the call to toJSON call in the stringification process, after the node creation? It would be a little more involved but maybe more powerful in the end?

**Comment by qraynaud** [comment]
You really made the right choice here. Anything else would be too complicated for the feat I'm afraid.

I think the only thing that might have helped me and would be great is to provide the function I gave you by default in the utils. Something like `stringifyJS` that would take any input and do the right thing without having to think much about it.

**Comment by eemeli** [comment]
I left this open earlier in case I thought of a way of providing something like an easy-to-use generic node stringifier, but I'm going to close it as wontfix, at least for now. Practically speaking, it's too useful for the library to internally presume that all nodes will inherit from one of scalar, alias, map, or sequence.

It's certainly possible for an external user to implement a ploymorphic node (as is done here), and end up with the desired results, but I don't think it makes sense to add a utility function for that to the library, esp. as it would not be used by any internal tooling.
