### ISSUE TITLE
Throwing error on special character

### ISSUE THREAD

**Issue by iamisti** [eemeli/yaml#247]
**Describe the bug**
When parsing a text that contains `PropertyName: @somethinghere`, then yaml parse fails with the error message:
'YAMLSemanticError: Plain value cannot start with reserved character @'

**To Reproduce**
Get a string like "ProtpertyName: @sometexthere" and use YAML.parse(thestring);

**Expected behaviour**
Text gets parsed without error

**Versions (please complete the following information):**

- Environment: Node 14.16.0
- `yaml`: v1.10.2

**Comment by eemeli** [comment]
`@` is a reserved character in YAML, so this is [working as intended](https://yaml.org/spec/1.2/spec.html#id2774228)

**Comment by iamisti** [comment]
@eemeli how is it a workaround? I only see definitions.

**Comment by eemeli** [comment]
If you can, the best way of fixing this is to quote the value in the original file: `'@somethinghere'`.

If you'd like to ignore the parse error, you should use `YAML.parseDocument()` rather than parse, and then remove the parse error from the `doc.errors` array. Right now, the only real way of identifying this error in particular is via the error message, and that admittedly isn't a guaranteed-stable API. I may need to consider adding error codes, or something.

**Comment by iamisti** [comment]
YAML.parseDocument() does not work either. Just thought I report it back

**Comment by eemeli** [comment]
Could you clarify what you mean by "does not work either"?

**Comment by iamisti** [comment]
it does not throw an error, but it also doesnt parse anything

**Comment by eemeli** [comment]
Really?

```js
const doc = YAML.parseDocument('PropertyName: @somethinghere')
doc.errors = []
doc.toJSON()
// { PropertyName: '@somethinghere' }
```

**Comment by eemeli** [comment]
Closing as answered.
