### ISSUE TITLE
Add Ranges to Error

### ISSUE THREAD

**Issue by gorkem** [eemeli/yaml#254]
**Is your feature request related to a problem? Please describe.**
YAMLErrors do not have a full range but instead they only report the offset of the error. 

**Describe the solution you'd like**
YAMLError to include range of the Error occurred

**Describe alternatives you've considered**
a visitor could be done to visit the nodes and determine the end offset.

**Additional context**
also discussed on https://github.com/redhat-developer/yaml-language-server/issues/421

**Comment by eemeli** [comment]
What should the range be, when the error is originally encountered at a specific location?

This is tough to always determine at the point at which the error happens, because the end of the node may well be still unknown at the time.

For your use case, would it be sufficient to provide a way to determine from an error the nearest surrounding sensible range?
