### ISSUE TITLE
Pair does not have a range

### ISSUE THREAD

**Issue by gorkem** [eemeli/yaml#256]
**Describe the bug**
I see an undefined `range` for a `Pair` even though the `Pair.key` and `Pair.value` exist and have correct ranges.  Is this expected?

**To Reproduce**
The string that  I have parsed` '---\n# a comment\ntest: test'`

**Expected behaviour**
Pair to have correct range values

**Comment by eemeli** [comment]
That is expected behaviour. With the parser change, [Pair](https://github.com/eemeli/yaml/blob/master/src/nodes/Pair.ts) became a really rather simple `{ key, value }` data holder. In other words, it explicitly does not `extend Node` and can no longer have comments associated with it, rather than its `key` and `value` nodes.
