### ISSUE TITLE
comments before a directive

### ISSUE THREAD

**Issue by gorkem** [eemeli/yaml#257]
**Describe the bug**
comments before a directive are not reflected on the AST. 

**To Reproduce**
String to test `'# a comment\n%TAG !yaml! tag:yaml.org,2002:\n---test: test'`

**Comment by eemeli** [comment]
The comment is not lost, it's misplaced. Which is a bug:

```js
const src = '# a comment\n%TAG !yaml! tag:yaml.org,2002:\n---test: test'
const doc = YAML.parseDocument(src)
doc.contents.items[0].key.commentBefore === ' a comment'
```

**Comment by eemeli** [comment]
Actually, the real bug here was that the original input is not marked as an error, due to a missing directives-end/doc-start marker. If you add a newline after the `---` the comment is correctly positioned:

```js
const src = '# a comment\n%TAG !yaml! tag:yaml.org,2002:\n---\ntest: test'
const doc = YAML.parseDocument(src)
doc.commentBefore === ' a comment'
```

Without a directive or a document marker, a comment needs an empty line after it to be considered a comment on the document, rather than the first content node:

```js
const src = '# a comment\n\ntest: test'
const doc = YAML.parseDocument(src)
doc.commentBefore === ' a comment'
```

**Comment by gorkem** [comment]
What if we only have comment `# a comment`? Even when I add the new lines I do not get a document in that case.

**Comment by eemeli** [comment]
Could you post the exact calls that are giving you output different from your expectations?

**Comment by gorkem** [comment]
Here is a[ test case ](https://github.com/gorkem/yaml/commit/fa00bcd90dc0137783762c5f14838b9352d3f851).
