### ISSUE TITLE
Escaping is doubled when colon is last character

### ISSUE THREAD

**Issue by dgsmith2** [eemeli/yaml#312]
**Describe the bug**

Escaping is doubled when colon is last character

**To Reproduce**
```ts
yaml.stringify('smile\\nlol')  // "smile\\nlol\n"
yaml.stringify('smile\\nlol:') // "\"smile\\\\nlol:\"\n"
```

**Expected behaviour**
```ts
yaml.stringify('smile\\nlol:') // "smile\\nlol:\n"
```

**Versions (please complete the following information):**
- `Node.js`: 14.17.4
- `yaml`: 1.10.2

**Comment by eemeli** [comment]
This is working as intended. A trailing `:` colon is not allowed here for a plain (unquoted) scalar, so the input needs to be quoted. And then because the quoted string is shorter than `doubleQuotedMinMultiLineLength` (defaults to 40), the `\n` is escaped.

Also note, regarding your expected behaviour:

```js
YAML.parse("smile\\nlol:\n") // { 'smile\\nlol': null }
```

**Comment by dgsmith2** [comment]
@eemeli thanks for the thorough explanation. Can you direct me to the doc/spec for this?  I assumed it was a bug because when I compared the output of another YAML library the output differed.  Thanks!

**Comment by dgsmith2** [comment]
I'm still trying to sort out what I am missing.  This is a bit more true to form of my use case:
```js
var yaml = require('yaml')
var jsYaml = require('js-yaml')

var unquoted = { text: 'foo\\nbar:' };
var quoted = { text: '"foo\\nbar:"' };

yaml.stringify(unquoted); // \"foo\\\\nbar:\"\n
jsYaml.dump(unquoted); //    'foo\\nbar:'\n

yaml.stringify(quoted); // '\"foo\\nbar:\"'\n
jsYaml.dump(quoted); //    '\"foo\\nbar:\"'\n
```
- Since strings have to be quoted in Javascript, why aren't they considered to be quoted scalars?
- Is it a difference in the YAML version implemented?

**Comment by eemeli** [comment]
The difference that you're observing is due to a difference in the libraries' default preference on quoting style, i.e. `"double"` vs. `'single'` quotes. It's exaggerated by copy-pasting the values from an output that is displaying the value of the string with JS quotes as well. Try this instead:

```js
> console.log(YAML.stringify({ text: 'foo\\nbar:' }))
text: "foo\\nbar:"

> console.log(YAML.stringify({ text: 'foo\\nbar:' }, { singleQuote: true }))
text: 'foo\nbar:'

```

Note that there you're seeing the exact characters that are in the output string. The `\\` is doubled in the first because the YAML double-quoted style allows for `\` as an escape character, so `\n` would otherwise get treated as a newline when the value is re-parsed.
