### ISSUE TITLE
Sequence items must not have preceding content on the same line

### ISSUE THREAD

**Issue by jzavisek** [eemeli/yaml#38]
It seems that the parser is unable to parse nested arrays in some cases.

### Version:
1.0.0-rc.7

### Steps to reproduce:
```
const YAML = require('yaml').default

const yamlContent = 
`
content:
  arrayOfArray:
  -
    - first: John
      last: Black
    - first: Brian
      last: Green
  -
    - first: Mark
      last: Orange
  -
    - first: Adam
      last: Grey
`

console.log(YAML.parse(yamlContent))
```

### Result:
```
YAMLSemanticError: Sequence items must not have preceding content on the same line
```

### Expected result:
Parsed JS object with nested arrays.

**Comment by eemeli** [comment]
Thank you @jzavisek for finding & reporting this!

The bug here was related to #10, with an internal `atLineStart` boolean indicator not also getting reset along with the `lineStart` offset when parsing a sequence value that followed another sequence value that had needed to check the indentation of its subsequent line. The particular corner-case where this got triggered required an indented not-first sequence item consisting itself of a sequence followed by another sequence value, i.e. at least this (note the leading indentation):
```
 -
 - - a
 -
```
