### ISSUE TITLE
Add support for configuring padding surrounding items in flow collections

### ISSUE THREAD

**Issue by cemerick** [eemeli/yaml#419]
I am looking to meet some user expectations/preferences in how flow collections are rendered in YAML that we generate. Specifically, I'd like to avoid the single-space padding that is currently hard-coded around flow collection items:

https://github.com/eemeli/yaml/blob/8e7e57f2ed478213509af2e97bbe7b2395ad5a91/src/stringify/stringifyCollection.ts#L158

Would you be open to adding a node-level formatting option (much like `spaceBefore`, etc) to control the size of this padding?

(FWIW, I've looked at using CSTs, but the prospect of building up documents using them vs. the much simpler AST is daunting. Note that these documents are being generated, not parsed from some existing source and modified; if that were the case, then using the CST facilities would be a snap. I can imagine a stringify approach that first distilled an AST to some default CST tree, which one could then modify as desired, but ofc that's not how things are set up. :smile:  )

**Comment by eemeli** [comment]
Sure, the internal padding for single-line flow collections could be made configurable. I think it's more of a [ToString Option](https://eemeli.org/yaml/#tostring-options) though? As in, I don't see the need to have this be configurable on a per-node basis, rather than as an overall rule to use for all collections.

**Comment by cemerick** [comment]
Oh sure, that will work, too. Will have a PR for you shortly.
