### ISSUE TITLE
Parse() emit warning on console for unresolved tag, unexpected use of console and parse "success"

### ISSUE THREAD

**Issue by gallofeliz** [eemeli/yaml#430]
**Is your feature request related to a problem? Please describe.**

When I misuse tags, I have

```
(node:156302) [TAG_RESOLVE_FAILED] YAMLWarning: Unresolved tag: !env at line 6, column 15:

    envTest2: !env {a: SHELL MOO}
              ^^^^

(Use `node --trace-warnings ...` to show where the warning was created
```

And a (not totally well) parsed document is returned to my code.

There are two problems for me :
- For my code, everything is okay. The end user will not see the problem and the application will start with corrupted parsed document.
- I always use loggers and all my logs are JSON formatted. Here we have a direct use of console.warn.

**Describe the solution you'd like**

- Ability to define to parse() that warnings should be interpreted as errors.
- And/Or ability to inject logger
- And/Or emit events / call a callback to capture warnings

**Describe alternatives you've considered**

By default, I will extract parse() code and call directly parseDocument(), but as I want to have yaml->js, it's more work and code on my side. 

**Additional context**

Is it necessary ? Ask to fill it.

What solution do you prefer ?

Regards

**Comment by eemeli** [comment]
In Node.js (and elsewhere if available), the warnings actually use `process.emitWarning()` rather than `console.warn()`. See the [Node.js docs](https://nodejs.org/api/process.html#processemitwarningwarning-options) for how to attach a listener for custom handling thereof, i.e. injecting your logger.

if that's not sufficient and you need to e.g. treat warnings as errors, then I'd recommend you write your own wrapper around `parseDocument()` for that. That's effectively what `parse()` does: https://github.com/eemeli/yaml/blob/35764085bec81eb075ad16241508de0934ec3477/src/public-api.ts#L136-L143

**Comment by gallofeliz** [comment]
Ok. I will do that. Thanks.
