### ISSUE TITLE
Is there a way to sort object keys when stringifying?

### ISSUE THREAD

**Issue by rodrigolive** [eemeli/yaml#44]
Is there an option or way of sorting keys when stringifying objects? Right now it seems random (as keys are randomly hashed in memory in the browser and Node I believe).

When stringifying JS objects, it is very important to get a predictable YAML that can be diffed and easily read by a human, which translates into having the keys from an object sorted.

Example:

```
console.log( YAML.stringify({ c: 30, a: 10, b: 20 }) );
// would print the following every time:
a: 10
b: 20
c: 30
```

**Comment by eemeli** [comment]
In order to sort the items during stringification, you'll need to turn your object into the contents of a `YAML.Document`:
```js
const doc = new YAML.Document()
doc.contents = YAML.createNode({ c: 30, a: 10, b: 20 }, false)
```

See [`YAML.createNode`](https://eemeli.org/yaml/#creating-nodes) for documentation of the above. The reason why you need a separate document object wrapping the collection is that it encodes the schema and other aspects that influence the string output.

At this point, `doc.contents.items` is an array of key/value pairs, which you may then sort to influence the eventual stringified order

```js
doc.contents.items.sort((a, b) => a.key < b.key ? -1 : a.key > b.key ? 1 : 0)
```

Now calling `String(doc)` will get you the order you wanted:
```yaml
a: 10
b: 20
c: 30
```

**Comment by murrayju** [comment]
I would love to see an option exposed at the YAML.stringify() level that would do this for you at all levels of the document. Having stable output (object keys always in the same order) is hugely important for any documents that need to be compared by humans in a diff tool.

**Comment by murrayju** [comment]
In case anyone finds this useful, [here is a (recursive) stable stringify implementation](https://runkit.com/murrayju/5e14c43a95ac51001ac19fc7).

**Comment by brandonkal** [comment]
Thank you @murrayju

**Comment by eemeli** [comment]
@murrayju I ended up adding a `sortMapKeys` option in a5e6fbc, which takes either a boolean `true` to sort using `<`, or a function `sort(a, b): int` for a custom approach (`a` and `b` are YAML `Pair` objects).

It works like this:
```
const obj = { b: 2, a: 1, c: 3 }
YAML.stringify(obj, { sortMapEntries: true })
// 'a: 1\nb: 2\nc: 3\n'

const sortMapEntries = (a, b) => (a.key < b.key ? 1 : a.key > b.key ? -1 : 0)
YAML.stringify(obj, { sortMapEntries })
// 'c: 3\nb: 2\na: 1\n'
```

The Collection mutator methods `add()` and `set()` will also obey this setting, if set.
