### ISSUE TITLE
feat: reduce size

### ISSUE THREAD

**Issue by linonetwo** [eemeli/yaml#481]
**Is your feature request related to a problem? Please describe.**

We want to add yaml support to tiddlywiki https://github.com/Jermolene/TiddlyWiki5/issues/7534 , but we hope this dependency can be smaller. Do you know some way to shink the size, for user that only want minimal serialize/deserialize feature, without things like "YAML comments and blank lines" or feature that won't needed in the metadata.

**Describe the solution you'd like**

Maybe do tree shaking, if this is modular?

**Describe alternatives you've considered**

Create a fork under your guidance, and strip most of the features.

**Additional context**

I hope it can be reduced to less than or around 10kb, like https://www.npmjs.com/package/json-to-pretty-yaml , while currently its 660 kB https://www.npmjs.com/package/yaml

**Comment by eemeli** [comment]
The 660 kB is just the npm package size; as you'll find from a cursory inspection, that includes two separate builds of the library. I'd recommend you try yourself what you end up with after tree shaking, minification and compression. Fundamentally, though, this is a library that attempts to be powerful rather than lean.

**Comment by eemeli** [comment]
Closing as there's not really anything to do here.
