### ISSUE TITLE
Missing error.source for 'SyntaxError: Document is not valid YAML (bad indentation?)'

### ISSUE THREAD

**Issue by ikatyang** [eemeli/yaml#5]
I'm not sure if this is intended, but if so, is it safe to rely on that `error.source === null` means the error range is the entire document?

**Comment by eemeli** [comment]
That error was hopefully the only one that did not have a proper `source`, but it does now.

The error means that the input string could not be parsed into a single root object, probably because of a typo in indentation or mixing map & seq values in a collection. The node it should now point to is the first one past the discontinuity.

If you do still manage to get a `null` source, then yes, that can be interpreted to mean that there's something wrong with the whole document. But it should not happen.
