### ISSUE TITLE
`parseDocument(str, options = {}): Document` does not parse elements under `]` character occurrence in new line.

### ISSUE THREAD

**Issue by Krzysztof-Kolodziejczyk** [eemeli/yaml#543]
Example file:

```yaml
definitions:
  Response:
      errors:
        type: array
        items:
          $ref: '#/definitions/Error'
        example: [{
          "category": "BAD_REQUEST" 
        }]
  Error:
    type: object
    properties:
      category:
        type: string
```
For this case Error element won't be in result object due to `[` character under `"category": "BAD_REQUEST"`.

```yaml
definitions:
  Response:
      errors:
        type: array
        items:
          $ref: '#/definitions/Error'
        example: [{
          "category": "BAD_REQUEST"  }]
  Error:
    type: object
    properties:
      category:
        type: string
```
For above scenario text is parsed correctly.

**Comment by eemeli** [comment]
The example is invalid YAML, because the last line of
```yaml
        example: [{
          "category": "BAD_REQUEST" 
        }]
```
is insufficiently indented.

This library makes a specific affordance for cases when the last line contains exactly one flow-collection terminator which has its start on the same line as the mapping key, as in:
```yaml
        example: [
          { "category": "BAD_REQUEST" }
        ]
```

I am not comfortable with expanding this affordance and deviation from the spec further to cover your case.
