### ISSUE TITLE
`%TAG directive should contain exactly two parts`. Detects `tag prefix` as `comment`

### ISSUE THREAD

**Issue by RedCMD** [eemeli/yaml#545]
**Describe the bug**
`#tag:yaml.org,2002:` is detected as a `comment` under `%TAG`

**To Reproduce**
place `#` at the start of a tag prefix
`%TAG !abc! #tag:yaml.org,2002: #comment`

**Expected behaviour**
`#tag:yaml.org,2002:` should be detected as [ns-tag-prefix](https://yaml.org/spec/1.2.2/#rule-ns-tag-prefix)

- Environment: VSCode 1.89
- `yaml`: `2.4.2`

**Additional context**
```yaml
%TAG directive should contain exactly two partsYAML
[
  {
    "name": "YAMLParseError",
    "code": "BAD_DIRECTIVE",
    "message": "%TAG directive should contain exactly two parts at line 1, column 1:\n\n%TAG !abc! #tag:yaml.org,2002: #comment\n^^^^^^^^^^\n",
    "pos": [
      0,
      10
    ],
    "linePos": [
      {
        "line": 1,
        "col": 1
      },
      {
        "line": 1,
        "col": 11
      }
    ]
  }
]
```
![image](https://github.com/eemeli/yaml/assets/33529441/c5348fb8-0156-4e93-a7ac-ba8734d0a768)
http://ben-kiki.org/ypaste/data/104318/index.html

**Comment by eemeli** [comment]
I think you're right, that's a bug. Starting a tag prefix with `#` may not have been considered when the spec was put together.

Would you be interested in filing a PR adding a test and fixing this?

**Comment by RedCMD** [comment]
I wouldn't know where to start

**Comment by eemeli** [comment]
Ah, there's a requirement in the [spec text](https://yaml.org/spec/1.2.2/#global-tag-prefix) that isn't included in the productions:

> If the [global tag] prefix begins with a character other than “`!`”, it must be a valid URI prefix, and should contain at least the scheme.

For URIs, we refer to RFC 3986, which includes this for the [scheme](https://datatracker.ietf.org/doc/html/rfc3986#section-3.1):

```abnf
scheme = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )
```

The spec even includes [an example](https://yaml.org/spec/1.2.2/#example-invalid-verbatim-tags) with an error for not matching the URI production, for verbatim tags.

So, because `#` isn't an [ALPHA](https://datatracker.ietf.org/doc/html/rfc2234#section-6.1) character, it must start a comment. And therefore the originally reported error is correct.

**Comment by RedCMD** [comment]
so the [rule-ns-tag-char](https://yaml.org/spec/1.2.2/#rule-ns-tag-char) spec should technically be updated to to `ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )`? (equivalent(?) and hex codes)

**Comment by eemeli** [comment]
Or something like that. We're discussing this now among the YAML core group. In any case, the current behaviour of this library is valid.

**Comment by eemeli** [comment]
Closing, as there's nothing actionable for this library.
