### ISSUE TITLE
`[+-].nan` incorrectly supported?

### ISSUE THREAD

**Issue by RedCMD** [eemeli/yaml#546]
**Describe the bug**
`+.nan` and `-.nan` are parsed as `.nan`

**To Reproduce**
```yaml
+.nan: +.nan 
+.nan: +.nan
-.NaN: -.NaN
-.NaN: -.NaN
.NAN: .NAN
.NAN: .NAN
```
(Github correctly ignores `[+-].nan`, but also seems to interpret `-` as `seq`)

**Expected behaviour**
`[+-].nan` should be parsed as type `str`

[tag-resolution](https://yaml.org/spec/1.2.2/#1032-tag-resolution)

- Environment: VSCode 1.89
- `yaml`: `2.4.2`

**Additional context**
also no error is given when multiple keys are given with the same value of type `.nan`

![image](https://github.com/eemeli/yaml/assets/33529441/c21e79ce-57d5-40e1-8af5-05446bb4795f)
![image](https://github.com/eemeli/yaml/assets/33529441/f584b8a1-e36e-4f6c-a9bb-4d1d69b08f2b)

**Comment by eemeli** [comment]
Not complaining about `-.nan` and `+.nan` is indeed a bug.

The lack of errors for multiple `NaN` keys is because `NaN !== NaN` in JavaScript, and `===` is what's used by `uniqueKeys: true`, the default. If this is important to you, it's possible to use e.g. a [SameValueZero](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness#same-value-zero_equality) implementation as the `uniqueKeys` option value.
