### ISSUE TITLE
`map` parsed as `string`

### ISSUE THREAD

**Issue by RedCMD** [eemeli/yaml#550]
**Describe the bug**
a flow map with an empty value should be parsed as `map`, not `string`
Flow nodes and flow keys are not allowed to contain the character set `:]`

**To Reproduce**
```yaml
[a:b]
---
[c:]
---
[:]
---
a:b
---
c:
---
:
```

**Expected behaviour**
`[c:]` should be a `map` with `c` key and _`empty`_ for the value
`[a:b]` is correctly parsed as a string
`[:]` is correctly parsed as an empty map

**Versions:**
- Environment: VSCode `1.89`
- `yaml`: `2.4.3`

**Additional context**
![image](https://github.com/eemeli/yaml/assets/33529441/bff3fd32-2b5c-4763-9685-0ee92125a330)

**Comment by eemeli** [comment]
> `[c:]` should be a `map` with `c` key and _`empty`_ for the value

Agreed, there's something wrong in the `ns-plain-char` lookahead, which should recognise the `]` after the `:` as a `c-flow-indicator`, so that this parses the same as `[c:,]` or `[c: ]`.

> `[:]` is correctly parsed as an empty map

To be picky, it's a sequence with a map as a value, and that map has a single pair with empty key and value. But it is indeed correctly parsed.
