### ISSUE TITLE
Stringify method remove Date Objects with empty object

### ISSUE THREAD

**Issue by seiya-git** [eemeli/yaml#63]
Stringify method remove Date Objects with empty object

```javascript
const yaml = require('yaml');
const myDate = new Date();
const yamlStr = yaml.stringify(myDate);
console.log(myDate);
console.log(yamlStr);
```
output:
```
2018-12-22T07:29:51.234Z
```
```
{}

```

**Comment by Hamper** [comment]
With timestamp tag also don't work:
```javascript
const yaml = require('yaml')
const { timestamp } = require ('yaml/types/timestamp')

yaml.defaultOptions.tags = [timestamp]

let x = yaml.parse('2018-12-22 08:02:52')
// 2018-12-22T08:02:52.000Z
yaml.stringify(x)
// '{}\n'
```

**Comment by eemeli** [comment]
This turned out to be two different but overlapping issues.

The original posted by @seiya-git was due to the internally-called `createNode` function not looking for a `toJSON` method on the input value (as provided e.g. by `Date`). Adding support for this should also help in other cases, such as Immutable.js collections.

In the case posted by @Hamper the mistake was in calling the schema-free `createNode` in the first place, as the right thing to do here is to keep the value as a `Date` and to get the `!!timestamp` tag to handle it directly. That should now happen thanks to an `instanceof tagObj.class` lookup, and it's even further customisable by defining a `tagObj.createNode(value)` function (required for non-scalar custom tags).

As these technically count as new features, I'll include them in the next minor release, probably at the same time as adding blank-line support. I'm also tempted to add support for [`!!set`](https://yaml.org/type/set.html) using the new `tagObj.createNode` functionality.

Once released, this is how it'll work:
```js
const date = new Date('2018-12-22T08:02:52Z')

YAML.stringify(date)
  // '2018-12-22T08:02:52.000Z\n'

YAML.stringify(date, { version: '1.1' })
  // '2018-12-22T08:02:52\n'
```
