### ISSUE TITLE
Support for JS Symbols

### ISSUE THREAD

**Issue by isaacs** [eemeli/yaml#77]
It would be nice if this module could either handle JavaScript Symbol objects, or provide some facility to define custom types such that one could add support in userland.

js-yaml has support for custom types, but they rely on providing a class, and `instanceof` returning true.  However, `Symbol('x') instanceof Symbol` is always false (even though `Object.getPrototypeOf(Symbol('x')) === Symbol.prototype`, because sometimes JS is wat!?)  I could wrap them in a SymbolWrap class and unwrap on parse, but ugh.

Context: I'm working on refactoring the yaml handling in node-tap, and one common complaint is that Symbol objects cause a throw.

**Comment by isaacs** [comment]
With that change, this seems to work sort of: https://gist.github.com/isaacs/d79a73009de66385075cf0f66093f53e

Any feedback would be welcome.  Thanks!

**Comment by eemeli** [comment]
That's very wat. I think the right thing to do here would be to extend the check as you suggested. Any particular reason why you'd prefer the `Object.getPrototypeOf` check instead of e.g. this?

```js
const match = this.tags.filter(
  t =>
    t.class &&
    (obj instanceof t.class || (obj && obj.constructor === t.class))
```

Slightly longer-term, I've been considering replacing the tag `class` properties with a boolean-returning function, which would allow for more generically matching JS objects or arrays to custom tags. Hence why I'd rather apply a quick-fix for now, rather than extending the tag object spec.

For the other primary types, the `typeof` checks effectively get subsumed into the `class` checks by the immediately preceding switch case, but for Symbol I'd just assumed that it'd work in a sensible manner.

**Comment by isaacs** [comment]
Yeah, `obj.constructor` is totally a fine way to go.  No reason to pick one over the other, imo.

> considering replacing the tag class properties with a boolean-returning function

That seems extremely sensible.  Then you can also put whatever other logic in there that makes sense, like sniffing at fields or string formatting.

> for Symbol I'd just assumed that it'd work in a sensible manner
That'll teach ya ;P

**Comment by isaacs** [comment]
I think #79 addresses this well enough for now.
