### ISSUE TITLE
Support circular objects (using Anchors?)

### ISSUE THREAD

**Issue by isaacs** [eemeli/yaml#81]
Consider this js:

```js
const yaml = require('yaml')
const a = {}
a.a = a
console.log(yaml.stringify(a))
```

The result is a stack overflow, which is not very good.  I'd really like to avoid having to work around this by sanitizing objects prior to sending to the yaml stringifier.

One solution would be to keep a list of all the objects visited earlier in a traversal, and print `[Circular]` or something.

Another would be to take advantage of [yaml anchors](https://sourceforge.net/p/yaml/mailman/message/10965262/), so the above object would stringify as:

```yaml
---
&generated_anchor
a: *generated_anchor
...
```

or something?

You probably _don't_ want to litter the output with anchors on every map and sequence, so maybe it should only do this if it sees that an object is repeated and walks up to the parent instance to add the anchor where needed.

**Comment by isaacs** [comment]
It looks like this approach is used in js-yaml:

```
> jsYaml.safeLoad('a: &a\n  a: *a')
{ a: { a: [Circular] } }
> jsYaml.safeDump(_)
'a: &ref_0\n  a: *ref_0\n'
```

**Comment by eemeli** [comment]
I really like this idea. The right place for the JS -> YAML circular reference detector is almost certainly during `createNode`, which probably needs to track seen objects.

For the YAML -> part of the loop, we already have a detector, but for now it's just failing rather than returning an object.

**Comment by eemeli** [comment]
Sort of related, but not quite. I mean more what happens when you create a `YAML.Document` and while working with its contents end up assigning an object (possibly a node) to more than one place. Adding references between those while that document is then being stringified is tricky. So the point of my second paragraph was that at least to start with, doing it that way wouldn't work.

Accounting for references within a single treelike structure (as happens e.g. within any `YAML.stringify()` call) is relatively simpler, but I want to avoid having to break the existing API and having to do a major version bump because of this. I'll try and work on this over the next week or so, while travelling.

Btw, your sample case isn't valid YAML, as it's (1) referring to an anchor before it's defined, and (2) considering a value as both an alias node and a mapping. Presumably this is sort of what you intended?

```yaml
a: &a
  b: 1
b:
  <<: *a
  c: 2
```
When that's parsed as YAML 1.1, it becomes:
```js
{ a: { b: 1 }, b: { b: 1, c: 2 } }
```
As a side note, there probably is a way to model JS prototype chains using `<<` merge keys in the YAML representation, but that's unlikely to be actually relevant to any real-world use case.
