### ISSUE TITLE
Errors in browser builds after recent update

### ISSUE THREAD

**Issue by laggingreflex** [eemeli/yaml#83]
I'm using this in a webpack app, and updating from `1.1.0` to `1.3` started causing lots of errors like 

>Module not found: Error: Can't resolve '@babel/runtime/helpers/get' in 'C:\data\temp\repro-yaml-1.3\node_modules\yaml\browser\dist\schema'
 @ ./node_modules/yaml/browser/dist/schema/Map.js 21:35-72
 @ ./node_modules/yaml/browser/dist/Anchors.js
 @ ./node_modules/yaml/browser/dist/Document.js
 @ ./node_modules/yaml/browser/dist/index.js
 @ ./src.js

**Comment by eemeli** [comment]
To fix, install `@babel/runtime`. Here's what's now mentioned in the readme:
>It runs on Node.js 6 and later with no external dependencies, and in browsers from IE 11 upwards using `@babel/runtime` (Note: not included in dependencies, install separately).

Sort of in a bind with this one, as I'd really like to keep the no-dependencies situation, but for use in browsers the runtime really helps with file size. :/

**Comment by tripodsan** [comment]
would it be possible to make this an optional dependency? or is there another solution for this problem?

for project using node, it really makes no sense to draw in babel as dependency. maybe it should be a `devDependency`, since you only need it when building with webpack, right?

**Comment by eemeli** [comment]
Having `@babel/runtime` as a dev dependency doesn't help, as those aren't included in installs. It would be nice if optional dependencies worked, but they're unlikely to really work like you'd expect (see e.g. npm/npm#14185). So we're left with it as a direct dependency, which I figured is the least wrong right option atm. And yes, for most users this unfortunately means that you get about 624KB of unused code sitting in your `node_modules` directory.

For context, `@babel/runtime` is currently (1.4) a dependency of `yaml`, but is only used when run/compiled in an environment like Webpack which reads the `"browser"` field of package.json. Here's what the readme mentions about it:
> It runs on Node.js 6 and later with no external dependencies, and in browsers from IE 11 upwards (Note: `@babel/runtime` is used only by the `"browser"` entry point).

The logic that I went through to get here is that first of all it makes sense to use `@babel/runtime` in browsers builds, due to the measurable file size savings that it enables; these savings can't be re-captured during the application's minifications, but must be a part of the `yaml` library's own transpilation. This effectively does mean that we need to have `@babel/runtime` as a dependency, even if it's not used in Node.js environments.
