### ISSUE TITLE
No new line when calling setIn with an object

### ISSUE THREAD

**Issue by dmarchin** [eemeli/yaml#87]
Should be a new line when calling setIn.

```
const YAML = require('yaml');

const test = `
test:
    a: '1'
    b: '2'
    c: '3'
`
const doc = YAML.parseDocument(test);

doc.setIn(['test'], {
    a: "test",
    b: "test",
    c: "test"
});
console.log(doc.toString());
```

Result

```
test: a: test
  b: test
  c: test
```

Expected:

```
test: 
  a: test
  b: test
  c: test
```

**Comment by dmarchin** [comment]
Thanks! Any idea when this and https://github.com/eemeli/yaml/issues/85 will be released?

**Comment by eemeli** [comment]
This was a bug actually pretty closely related to #85. The `key: value` pair stringifier needs to decide when to stringify the value on its own line, and in this case it was deciding it wrong as the value isn't a node. Fixed by detecting this case and moving the value's wrapping as a node to the calling function.

There's sufficient stuff currently on master that the next from that is going to need a minor version increment, but I'll push out an off-branch patch release shortly with these fixes.

**Comment by dmarchin** [comment]
Awesome thank you, will that propagate to npm?
