### ISSUE TITLE
null in object value

### ISSUE THREAD

**Issue by gwh-cpnet** [eemeli/yaml#88]
version 1.3.2 

```es6
const YAML = require('yaml');
console.log(YAML.stringify({all: {a: null, b: null, c: null }}));
```
it would get
```
all:
  ? a
  ? b
  ? c
```

why `?` is here? and it is not even a valid yaml.

I suppose it should be 

```yaml
all:
  a: 
  b: 
  c: 
```

my goal can be verify on
https://codebeautify.org/yaml-to-json-xml-csv
https://www.json2yaml.com/

**Comment by eemeli** [comment]
This is in fact intentional, and [valid YAML](https://yaml.org/spec/1.2/spec.html#id2790832). `?` is an indicator for an explicit key, and it's used for mappings with all-null values. The presumption here is that such mappings are used as sets or set-like collections, where the unique keys rather than their values are the interesting feature, and using this form makes that more clear.

The [`!!set`](https://yaml.org/type/set.html) type was a part of the 1.1 version of the spec, and its examples use this form as well.

Setting any of the values to be non-null will use the `key: value` form for all collection items.

**Comment by gwh-cpnet** [comment]
oh, thank you. 

Your lib handle it well anyway.

```es6
const YAML = require('yaml');
console.log(YAML.parse(YAML.stringify({all: {a: null, b: null, c: null }})));
```

it would print
```
{ all: { a: null, b: null, c: null } }
```

In my use case, I was trying to generate inventory.yaml for [ansible](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html), ansible does not work with `?` for now.

**Comment by seansfkelley** [comment]
Is there a way to force `stringify` to serialize null-keyed objects with explicit `null` values? I don't see any options in the documentation that are suitable.

**Comment by eemeli** [comment]
@seansfkelley Could you give an example of what you mean?

**Comment by seansfkelley** [comment]
I imagine something like `yaml.stringify({ "foo": null }, { nullMapAsSet: false })` which would yield 

```yaml
foo: null
```

or perhaps (but dispreferred)

```yaml
foo:
```

instead of

```yaml
? foo
```

I have a use-case that relies on the small, most common subset of the YAML spec (the part that just looks like cleaner JSON -- no `!!`, `?`, aliases, etc.), and some of my code broke due to the unexpected serialization of an all-null map into the set-like form.

I couldn't find any such option in the documentation, if it exists. I was surprised that the serializer would try to do something "clever" without being explicitly configured to be so. To expand the scope a bit, perhaps such an option could be called `verbose` or `compact` or something along those lines?

**Comment by eemeli** [comment]
Okay, I'll concede that there may be a valid case here. I'll have a look at making this configurable.

**Comment by seansfkelley** [comment]
Awesome, thank you!
