### ISSUE TITLE
binary type not working in latest master?

### ISSUE THREAD

**Issue by isaacs** [eemeli/yaml#90]
```js
const YAML = require('yaml')
const tags = [ require('yaml/types/binary') ]
const data = Buffer.from('hello, world')
console.log(YAML.stringify(data, {tags}))
```

Output:

```
type: Buffer
data:
  - 104
  - 101
  - 108
  - 108
  - 111
  - 44
  - 32
  - 119
  - 111
  - 114
  - 108
  - 100
```

If I use `tags = [require('yaml/types/binary').binary]` then it works.  Was this an intentional change?  `omap` and `set` export the type without an extra property assignment.

**Comment by eemeli** [comment]
Oh, drat. It looks like I've managed to export arrays of tag objects from `yaml/types/binary` and `yaml/types/timestamp`, and tag objects from `yaml/types/{omap,pairs,set}`.

This should get fixed at least so that importing and using the types "just works", but I'm considering taking the opportunity to refactor the type exports to be a bit clearer than they are now.

**Comment by eemeli** [comment]
I've added a workaround for this specific issue by accepting arrays of tag objects in `tags`, and will open a separate issue regarding the package's exports more generally.
