### ISSUE TITLE
Unnecessary quote added to number key 

### ISSUE THREAD

**Issue by joshuaavalon** [eemeli/yaml#92]
## Test Code
```javascript
const fs = require("fs");
const yaml = require("yaml");

const str = fs.readFileSync("before.yaml", { encoding: "utf8" });
const data = yaml.parse(str);

const str2 = yaml.stringify(data);
fs.writeFileSync("after.yaml", str2, { encoding: "utf8" });
```

**before.yaml**
```yaml
1: foo
```

**after.yaml**
```yaml
"1": foo
```

## Expected Result

`before.yaml` should be the same as `after.yaml`

**Comment by eemeli** [comment]
In this case, the quotes around `"1"` are in fact necessary to accurately represent the input given to `YAML.stringify()`. YAML supports keys of any type, while JSON only supports string keys for objects. Specifically, `data` here is the object `{ 1: 'foo' }` where `1` is a string rather than the number as which it was first parsed. When then stringifying `'1'`, the first attempt will be to use a plain (i.e. unquoted) style, but it'll then check whether the output `1` would still be parsed as a string; this check fails, and the fallback in this case is to stringify it as `"1"`.

To get the result you expect, there are at least three different ways of using and configuring `yaml`:

1. Specify the `failsafe` schema for your stringifier, which only supports strings as a scalar type. As a consequence, the internal reparse-as-string check done on `1` will pass. Note that this will require all input scalars to be strings, so stringifying e.g. `[1, 2]` would fail.
    ```js
    const data = YAML.parse('1: foo') // { 1: 'foo' }
    YAML.stringify(data, { schema: 'failsafe' }) // '1: foo\n'
    ```

2. Parse the map as a JS Map object, which allows for retaining the parsed type of the key. In this case `1` will be stringified as a number, and therefore will not be quoted:
    ```js
    const data = YAML.parse('1: foo', { mapAsMap: true }) // Map { 1 => 'foo' }
    YAML.stringify(data) // '1: foo\n'
    ```

3. Rather than parsing the input into a native JS object, keep it as a YAML Document. This will allow for the key's type (as well as other attributes) to be fully retained:
    ```js
    const doc = YAML.parseDocument('1: foo') // Document { ... }
    doc.contents.items[0] // Pair { key: Scalar { value: 1 }, value: Scalar { value: 'foo' } }
    String(doc) // '1: foo\n'
    ```
