### ISSUE TITLE
float is not parsed properly

### ISSUE THREAD

**Issue by imagecmos** [eemeli/yaml#97]
my local version is 1.4.0
the case like this
`YAML.parse("foo: !!float 3.0")`
`YAML.parse("foo: 3.0")`
the result always is
`{ foo: 3 }`
the right result is not `{ foo: 3.0 }`?

**Comment by eemeli** [comment]
Could you clarify how you think that the JS representation of the value `3.0` should differ from its representation of the value `3`?

**Comment by imagecmos** [comment]
> Could you clarify how you think that the JS representation of the value `3.0` should differ from its representation of the value `3`?

we have a web page, users can edit their config then push it to target path
so we want the content of the config is the same as what users input

**Comment by eemeli** [comment]
The answer I was intending to give here was to use `YAML.parseDocument()` rather than `YAML.parse()`, but it turns out that the `!!float` tag is lost even then. That probably shouldn't happen. I'll test a bit more, and possibly tweak the number stringifier to keep the tag.

**Comment by eemeli** [comment]
Actually, I'll need to refactor the tag object a bit to accommodate this.

**Comment by eemeli** [comment]
With the most recent change, we get this:

```js
const doc = YAML.parseDocument('foo: !!float 3.0') 
String(doc) === 'foo: !!float 3\n'
```

Effectively, I've made it so that explicit tags in the source correspond to explicit tags in the AST nodes, both when parsing as well as stringifying.

I'm considering what -- if anything -- to do about the `.0` part. For instance, if you first parsed `3.0` as a float and then updated its value to 30, would you expect it to be stringified as `30` or as `30.0`? Similarly, if you parsed `3.10` and updated its value to 30, how should that be stringified?

**Comment by eemeli** [comment]
Closing this as fixed. When a non-scientific float is now parsed, if its value has `0` as the last fraction digit, it sets a property `minFractionDigits` for the resolved node, which is then used during stringification. So if you update a value that was parsed from `3.0` to 30, it'll be stringified as `30.0`:

```js
const doc = YAML.parseDocument('foo: !!float 3.0\nbar: 4.20e3')
// In order to keep the explicit tag & minFractionDigits we need to fetch and
// modify the original node, rather than using set() to overwrite its value.
const float = doc.get('foo', true)
float.value = 30
String(doc)
// foo: !!float 30.0
// bar: 4.2e+3
```

Setting `minFractionDigits` on a scalar node with a Number `value` will control the string output, provided that its `format` is empty and its `tag` is either empty, or set to `'tag:yaml.org,2002:float'`.

Exponential values now keep that form, but their fraction digits aren't remembered. This is due to needing to use [Number#toExponential()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toExponential) to stringify them, as [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) doesn't [yet](https://github.com/tc39/proposal-unified-intl-numberformat) support them.
