### ISSUE TITLE
Source Mapping?

### ISSUE THREAD

**Issue by champgm** [eemeli/yaml#98]
This probably isn't the right place to ask this, but does `yaml` support any kind of source mapping?

I'm working on a project where I want to parse a file, do various syntax and reference checking tasks, then take action if problems are found. When I find "problems" I need to be able to trace them back to the line and column numbers at which they occur in the source file.

**Comment by eemeli** [comment]
Yes, but you'll need to use `YAML.parseDocument()` rather than `YAML.parse()`. That'll get you an AST tree of the YAML document, and each node has a `range: [startIdx, endIdx]` member. To get line/column positions rather than character indices, you'll need to enable the `keepCstNodes` option, which will provide each node with a getter at `cstNode.rangeAsLinePos`, providing the `start` & `end` positions as `{ line, col }` pointers.

With this approach, you would need to work with YAML collections rather than the pure-JS objects and arrays that `YAML.parse()` provides, but that should be relatively painless with their `get()` and `getIn()` accessor methods.

Alternatively, you might be able to implement your syntax & reference checks as custom YAML types, which would effectively result in parse errors on failures, which would also provide the relevant CST node as its `source`. Without knowing (much) more details about what you're really doing, it's hard to say whether this approach would make sense for you.

**Comment by champgm** [comment]
@eemeli Thanks a ton, this seems to be working okay so far. I hit a bit of a snag when I tried to call `get` on a `YAML.ast.Document` object (I am writing Typescript and using `@types/yaml`) and saw that the method wasn't listed in the typings, but I've fallen back to casting it as an `any` and using a debugger to explore its structure.

If you're curious about what exactly I'm working on, it's a VS Code extension, the parsing part starts about here: https://github.com/champgm/cloudformation-yaml-validator/blob/78f35c20215a7eccde0c031e954e4e4bc9cc27ba/src/CloudformationYaml.ts#L48

I'll go ahead and close this since I seem to be making good progress. Thanks again for your help!

**Comment by eemeli** [comment]
Ah, feel free to submit an update to DefinitelyTyped for `@types/yaml`. It hasn't been updated for last few minor updates, and I myself don't really use TypeScript.
